version: "3.8"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    depends_on:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - type: bind
        source: ./sonar
        target: /sonarqube
    ports:
      - 9876:9000
    networks:
      - sonarzart

  sonarqube-database:
    container_name: sonarqube-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgresql/data
    networks:
      - sonarzart

  sonar-scanner:
    container_name: sonar-scanner
    image: sonarsource/sonar-scanner-cli
    depends_on:
      - sonarqube
    environment:
      - SONAR_HOST_URL=http://sonarqube:9876
    volumes:
      - type: bind
        source: ./sonar
        target: /sonar-scanner
    command: tail -f /dev/null
    network_mode: host

networks:
  sonarzart:

volumes:
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:
